package com.example.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material.icons.filled.Security
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.components.OTPInput
import com.example.ui.components.RuralLinkButton
import com.example.ui.theme.AppBackground
import com.example.ui.theme.EmeraldGreen
import com.example.ui.theme.PrimaryDarkText
import com.example.ui.theme.SecondaryText

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TwoFactorAuthScreen(
    onBack: () -> Unit,
    onVerifySuccess: () -> Unit
) {
    var code by remember { mutableStateOf("") }
    var errorMessage by remember { mutableStateOf<String?>(null) }
    var isVerifying by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Two-Factor Authentication", fontWeight = FontWeight.Bold, fontSize = 18.sp) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = AppBackground,
                    titleContentColor = PrimaryDarkText,
                    navigationIconContentColor = PrimaryDarkText
                )
            )
        },
        containerColor = AppBackground
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(24.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Icon(
                imageVector = Icons.Default.Security,
                contentDescription = null,
                tint = EmeraldGreen,
                modifier = Modifier.size(80.dp)
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            Text(
                text = "Enter Authenticator Code",
                fontSize = 22.sp,
                fontWeight = FontWeight.ExtraBold,
                color = PrimaryDarkText
            )
            
            Spacer(modifier = Modifier.height(8.dp))
            
            Text(
                text = "For added security, please enter the 6-digit code generated by your Authenticator app. (Hint: Use 999999 for this demo)",
                fontSize = 14.sp,
                color = SecondaryText,
                textAlign = TextAlign.Center
            )
            
            Spacer(modifier = Modifier.height(32.dp))
            
            OTPInput(
                otpValue = code,
                onOtpChange = { 
                    code = it
                    errorMessage = null 
                },
                testTag = "2fa_input"
            )
            
            if (errorMessage != null) {
                Spacer(modifier = Modifier.height(16.dp))
                Text(
                    text = errorMessage ?: "",
                    color = Color(0xFFD32F2F),
                    fontSize = 13.sp,
                    fontWeight = FontWeight.Medium
                )
            }
            
            Spacer(modifier = Modifier.height(32.dp))
            
            RuralLinkButton(
                text = if (isVerifying) "Verifying..." else "Verify",
                onClick = {
                    if (code == "999999") {
                        isVerifying = true
                        onVerifySuccess()
                    } else {
                        errorMessage = "Invalid code. Please use 999999 for the demo."
                    }
                },
                icon = Icons.Default.Lock,
                enabled = !isVerifying,
                modifier = Modifier.fillMaxWidth()
            )
        }
    }
}
